version: '2'
services:
    jhipster_monolithic_example-app:
        image: jhipster_monolithic_example
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipster_monolithic_example-mysql:3306/jhipster_monolithic_example?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipster_monolithic_example-mysql:
        extends:
            file: mysql.yml
            service: jhipster_monolithic_example-mysql
